/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(iot_laptiming_PitStatusMessage, iot_laptiming_PitStatusMessage, AUTO)


PB_BIND(iot_laptiming_PitStatusResponse, iot_laptiming_PitStatusResponse, AUTO)


PB_BIND(iot_laptiming_LapTimeMessage, iot_laptiming_LapTimeMessage, AUTO)


PB_BIND(iot_laptiming_LapTimeResponse, iot_laptiming_LapTimeResponse, AUTO)


PB_BIND(iot_laptiming_TestMessage, iot_laptiming_TestMessage, AUTO)




