/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_IOT_LAPTIMING_MESSAGES_PB_H_INCLUDED
#define PB_IOT_LAPTIMING_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _iot_laptiming_PitStatus {
    iot_laptiming_PitStatus_UKNOWN = 0,
    iot_laptiming_PitStatus_PIT_ENTRY = 1,
    iot_laptiming_PitStatus_PIT_EXIT = 2
} iot_laptiming_PitStatus;

/* Struct definitions */
typedef struct _iot_laptiming_PitStatusMessage {
    int32_t id;
    bool has_timestamp;
    int64_t timestamp;
    bool has_pitStatus;
    iot_laptiming_PitStatus pitStatus;
} iot_laptiming_PitStatusMessage;

typedef struct _iot_laptiming_PitStatusResponse {
    char dummy_field;
} iot_laptiming_PitStatusResponse;

typedef struct _iot_laptiming_LapTimeMessage {
    int32_t id;
    int64_t lapTime;
    int64_t timestamp;
} iot_laptiming_LapTimeMessage;

typedef struct _iot_laptiming_LapTimeResponse {
    char dummy_field;
} iot_laptiming_LapTimeResponse;

typedef struct _iot_laptiming_TestMessage {
    bool enabled;
    int64_t timestamp;
} iot_laptiming_TestMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _iot_laptiming_PitStatus_MIN iot_laptiming_PitStatus_UKNOWN
#define _iot_laptiming_PitStatus_MAX iot_laptiming_PitStatus_PIT_EXIT
#define _iot_laptiming_PitStatus_ARRAYSIZE ((iot_laptiming_PitStatus)(iot_laptiming_PitStatus_PIT_EXIT+1))

#define iot_laptiming_PitStatusMessage_pitStatus_ENUMTYPE iot_laptiming_PitStatus






/* Initializer values for message structs */
#define iot_laptiming_PitStatusMessage_init_default {0, false, 0, false, _iot_laptiming_PitStatus_MIN}
#define iot_laptiming_PitStatusResponse_init_default {0}
#define iot_laptiming_LapTimeMessage_init_default {0, 0, 0}
#define iot_laptiming_LapTimeResponse_init_default {0}
#define iot_laptiming_TestMessage_init_default   {0, 0}
#define iot_laptiming_PitStatusMessage_init_zero {0, false, 0, false, _iot_laptiming_PitStatus_MIN}
#define iot_laptiming_PitStatusResponse_init_zero {0}
#define iot_laptiming_LapTimeMessage_init_zero   {0, 0, 0}
#define iot_laptiming_LapTimeResponse_init_zero  {0}
#define iot_laptiming_TestMessage_init_zero      {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define iot_laptiming_PitStatusMessage_id_tag    1
#define iot_laptiming_PitStatusMessage_timestamp_tag 2
#define iot_laptiming_PitStatusMessage_pitStatus_tag 3
#define iot_laptiming_LapTimeMessage_id_tag      1
#define iot_laptiming_LapTimeMessage_lapTime_tag 2
#define iot_laptiming_LapTimeMessage_timestamp_tag 3
#define iot_laptiming_TestMessage_enabled_tag    1
#define iot_laptiming_TestMessage_timestamp_tag  2

/* Struct field encoding specification for nanopb */
#define iot_laptiming_PitStatusMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, STATIC,   OPTIONAL, INT64,    timestamp,         2) \
X(a, STATIC,   OPTIONAL, UENUM,    pitStatus,         3)
#define iot_laptiming_PitStatusMessage_CALLBACK NULL
#define iot_laptiming_PitStatusMessage_DEFAULT NULL

#define iot_laptiming_PitStatusResponse_FIELDLIST(X, a) \

#define iot_laptiming_PitStatusResponse_CALLBACK NULL
#define iot_laptiming_PitStatusResponse_DEFAULT NULL

#define iot_laptiming_LapTimeMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, STATIC,   SINGULAR, INT64,    lapTime,           2) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         3)
#define iot_laptiming_LapTimeMessage_CALLBACK NULL
#define iot_laptiming_LapTimeMessage_DEFAULT NULL

#define iot_laptiming_LapTimeResponse_FIELDLIST(X, a) \

#define iot_laptiming_LapTimeResponse_CALLBACK NULL
#define iot_laptiming_LapTimeResponse_DEFAULT NULL

#define iot_laptiming_TestMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         2)
#define iot_laptiming_TestMessage_CALLBACK NULL
#define iot_laptiming_TestMessage_DEFAULT NULL

extern const pb_msgdesc_t iot_laptiming_PitStatusMessage_msg;
extern const pb_msgdesc_t iot_laptiming_PitStatusResponse_msg;
extern const pb_msgdesc_t iot_laptiming_LapTimeMessage_msg;
extern const pb_msgdesc_t iot_laptiming_LapTimeResponse_msg;
extern const pb_msgdesc_t iot_laptiming_TestMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define iot_laptiming_PitStatusMessage_fields &iot_laptiming_PitStatusMessage_msg
#define iot_laptiming_PitStatusResponse_fields &iot_laptiming_PitStatusResponse_msg
#define iot_laptiming_LapTimeMessage_fields &iot_laptiming_LapTimeMessage_msg
#define iot_laptiming_LapTimeResponse_fields &iot_laptiming_LapTimeResponse_msg
#define iot_laptiming_TestMessage_fields &iot_laptiming_TestMessage_msg

/* Maximum encoded size of messages (where known) */
#define iot_laptiming_LapTimeMessage_size        33
#define iot_laptiming_LapTimeResponse_size       0
#define iot_laptiming_PitStatusMessage_size      24
#define iot_laptiming_PitStatusResponse_size     0
#define iot_laptiming_TestMessage_size           13

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
